### ISSUE TITLE
Can't run the specs

### ISSUE THREAD

**Issue by guiocavalcanti** [redu/help-center#33]
```
help-center (master) > bundle exec rake sunspot:solr:run RAILS_ENV=test
help-center (master) > bundle exec rspec

BasicGuidesController
  GET new
    should render guides/new
  POST create
    should create a new basic guide (FAILED - 1)
    should be a root (FAILED - 2)
  POST update
    should update the basic guide (FAILED - 3)

FaqsController
  GET new
    should render faqs/new
  POST create
    should create a new faq (FAILED - 4)
    should be a root (FAILED - 5)
  POST update
    should update the faq (FAILED - 6)

GuidesController
  GET new
    should render guides/new
  POST create
    should create a new guide (FAILED - 7)
    should be a root (FAILED - 8)
  POST update
    should update the guide (FAILED - 9)

TopicsController
  GET index
    should render index (FAILED - 10)
    should load all roots from Guide (FAILED - 11)
    frequently questions list
      should load top questions in Faq (FAILED - 12)
  GET show
    faq
      should render faq (FAILED - 13)
      should load top_questions (FAILED - 14)
      should load all categories (FAILED - 15)
    faq category
      should render category show (FAILED - 16)
      should load all children (FAILED - 17)
      should load all ancestors (FAILED - 18)
    basic guide
      should render basic guide (FAILED - 19)
      should load all children (FAILED - 20)
    guide
      should render guide (FAILED - 21)
      should load all topics (FAILED - 22)
    topics
      should render show (FAILED - 23)
      should load all ancestors (FAILED - 24)
      should increase view_count (FAILED - 25)
      should load two topics to read more (FAILED - 26)
  New
    should render topics/new
    POST create
      should create a new topic (FAILED - 27)
      should be a leave (FAILED - 28)
      should have a guide as parent (FAILED - 29)
  Edit
    should render edit (FAILED - 30)
    should load all descendants (FAILED - 31)
    POST update
      should update the topic (FAILED - 32)
  GET edit_all
    should render edit_all
  POST destroy
    should delete the topic (FAILED - 33)
    should redirect to home path (FAILED - 34)

Topic
  creation
    should require title to be set
  get type
    is faq (FAILED - 35)
    is guide (FAILED - 36)
    is basic guide (FAILED - 37)
  read more
    with many leaves
      should retrieve two next leaves from guide (FAILED - 38)
      if topic is the last leaf
        should retrieve the leaves before (FAILED - 39)
      if topic is the penultimate leaf
        should retrieve one leaf before and the last one (FAILED - 40)
    with only one more leaf
      the last one
        should retrieve the first leaf (FAILED - 41)
      the first one
        should retrieve the last leaf (FAILED - 42)
    with no more leaf
      should retrieve any leaf (FAILED - 43)

Failures:

  1) BasicGuidesController POST create should create a new basic guide
     Failure/Error: post :create, @params
     NoMethodError:
       undefined method `cached_slug_changed?' for #<BasicGuide:0x007fb48a09f678>
     # ./app/controllers/basic_guides_controller.rb:12:in `create'
     # ./spec/controllers/basic_guides_controller_spec.rb:28:in `block (4 levels) in <top (required)>'
     # ./spec/controllers/basic_guides_controller_spec.rb:27:in `block (3 levels) in <top (required)>'

  2) BasicGuidesController POST create should be a root
     Failure/Error: post :create, @params
     NoMethodError:
       undefined method `cached_slug_changed?' for #<BasicGuide:0x007fb48a1f7a20>
     # ./app/controllers/basic_guides_controller.rb:12:in `create'
     # ./spec/controllers/basic_guides_controller_spec.rb:33:in `block (3 levels) in <top (required)>'

  3) BasicGuidesController POST update should update the basic guide
     Failure/Error: @basic = create(:basic_guide)
     NoMethodError:
       undefined method `cached_slug_changed?' for #<BasicGuide:0x007fb4892ffa18>
     # ./spec/controllers/basic_guides_controller_spec.rb:42:in `block (3 levels) in <top (required)>'

  4) FaqsController POST create should create a new faq
     Failure/Error: post :create, @params
     NoMethodError:
       undefined method `cached_slug_changed?' for #<Faq:0x007fb4893c5da8>
     # ./app/controllers/faqs_controller.rb:12:in `create'
     # ./spec/controllers/faqs_controller_spec.rb:31:in `block (4 levels) in <top (required)>'
     # ./spec/controllers/faqs_controller_spec.rb:30:in `block (3 levels) in <top (required)>'

  5) FaqsController POST create should be a root
     Failure/Error: post :create, @params
     NoMethodError:
       undefined method `cached_slug_changed?' for #<Faq:0x007fb48c10cf50>
     # ./app/controllers/faqs_controller.rb:12:in `create'
     # ./spec/controllers/faqs_controller_spec.rb:36:in `block (3 levels) in <top (required)>'

  6) FaqsController POST update should update the faq
     Failure/Error: @faq = create(:faq)
     NoMethodError:
       undefined method `cached_slug_changed?' for #<Faq:0x007fb48c732178>
     # ./spec/controllers/faqs_controller_spec.rb:45:in `block (3 levels) in <top (required)>'

  7) GuidesController POST create should create a new guide
     Failure/Error: post :create, @params
     NoMethodError:
       undefined method `cached_slug_changed?' for #<Guide:0x007fb48c7e12b8>
     # ./app/controllers/guides_controller.rb:12:in `create'
     # ./spec/controllers/guides_controller_spec.rb:28:in `block (4 levels) in <top (required)>'
     # ./spec/controllers/guides_controller_spec.rb:27:in `block (3 levels) in <top (required)>'

  8) GuidesController POST create should be a root
     Failure/Error: post :create, @params
     NoMethodError:
       undefined method `cached_slug_changed?' for #<Guide:0x007fb48c45d998>
     # ./app/controllers/guides_controller.rb:12:in `create'
     # ./spec/controllers/guides_controller_spec.rb:33:in `block (3 levels) in <top (required)>'

  9) GuidesController POST update should update the guide
     Failure/Error: @guide = create(:guide)
     NoMethodError:
       undefined method `cached_slug_changed?' for #<Guide:0x007fb48c466138>
     # ./spec/controllers/guides_controller_spec.rb:42:in `block (3 levels) in <top (required)>'

  10) TopicsController GET index should render index
     Failure/Error: create(:guide)
     NoMethodError:
       undefined method `cached_slug_changed?' for #<Guide:0x007fb48c6b0420>
     # ./spec/controllers/topics_controller_spec.rb:8:in `block (3 levels) in <top (required)>'

  11) TopicsController GET index should load all roots from Guide
     Failure/Error: create(:guide)
     NoMethodError:
       undefined method `cached_slug_changed?' for #<Guide:0x007fb48c4338a0>
     # ./spec/controllers/topics_controller_spec.rb:8:in `block (3 levels) in <top (required)>'

  12) TopicsController GET index frequently questions list should load top questions in Faq
     Failure/Error: create(:guide)
     NoMethodError:
       undefined method `cached_slug_changed?' for #<Guide:0x007fb488a586a8>
     # ./spec/controllers/topics_controller_spec.rb:8:in `block (3 levels) in <top (required)>'

  13) TopicsController GET show faq should render faq
     Failure/Error: @topic = create(:topic)
     NoMethodError:
       undefined method `cached_slug_changed?' for #<Topic:0x007fb4895fda58>
     # ./spec/controllers/topics_controller_spec.rb:43:in `block (3 levels) in <top (required)>'

  14) TopicsController GET show faq should load top_questions
     Failure/Error: @topic = create(:topic)
     NoMethodError:
       undefined method `cached_slug_changed?' for #<Topic:0x007fb48c26d1b0>
     # ./spec/controllers/topics_controller_spec.rb:43:in `block (3 levels) in <top (required)>'

  15) TopicsController GET show faq should load all categories
     Failure/Error: @topic = create(:topic)
     NoMethodError:
       undefined method `cached_slug_changed?' for #<Topic:0x007fb48a4d3690>
     # ./spec/controllers/topics_controller_spec.rb:43:in `block (3 levels) in <top (required)>'

  16) TopicsController GET show faq category should render category show
     Failure/Error: @topic = create(:topic)
     NoMethodError:
       undefined method `cached_slug_changed?' for #<Topic:0x007fb48c425de0>
     # ./spec/controllers/topics_controller_spec.rb:43:in `block (3 levels) in <top (required)>'

  17) TopicsController GET show faq category should load all children
     Failure/Error: @topic = create(:topic)
     NoMethodError:
       undefined method `cached_slug_changed?' for #<Topic:0x007fb48c2431d0>
     # ./spec/controllers/topics_controller_spec.rb:43:in `block (3 levels) in <top (required)>'

  18) TopicsController GET show faq category should load all ancestors
     Failure/Error: @topic = create(:topic)
     NoMethodError:
       undefined method `cached_slug_changed?' for #<Topic:0x007fb48a3e87a8>
     # ./spec/controllers/topics_controller_spec.rb:43:in `block (3 levels) in <top (required)>'

  19) TopicsController GET show basic guide should render basic guide
     Failure/Error: @topic = create(:topic)
     NoMethodError:
       undefined method `cached_slug_changed?' for #<Topic:0x007fb48c2171e8>
     # ./spec/controllers/topics_controller_spec.rb:43:in `block (3 levels) in <top (required)>'

  20) TopicsController GET show basic guide should load all children
     Failure/Error: @topic = create(:topic)
     NoMethodError:
       undefined method `cached_slug_changed?' for #<Topic:0x007fb489263898>
     # ./spec/controllers/topics_controller_spec.rb:43:in `block (3 levels) in <top (required)>'

  21) TopicsController GET show guide should render guide
     Failure/Error: @topic = create(:topic)
     NoMethodError:
       undefined method `cached_slug_changed?' for #<Topic:0x007fb488e13ef0>
     # ./spec/controllers/topics_controller_spec.rb:43:in `block (3 levels) in <top (required)>'

  22) TopicsController GET show guide should load all topics
     Failure/Error: @topic = create(:topic)
     NoMethodError:
       undefined method `cached_slug_changed?' for #<Topic:0x007fb4891b2ef8>
     # ./spec/controllers/topics_controller_spec.rb:43:in `block (3 levels) in <top (required)>'

  23) TopicsController GET show topics should render show
     Failure/Error: @topic = create(:topic)
     NoMethodError:
       undefined method `cached_slug_changed?' for #<Topic:0x007fb489235b50>
     # ./spec/controllers/topics_controller_spec.rb:43:in `block (3 levels) in <top (required)>'

  24) TopicsController GET show topics should load all ancestors
     Failure/Error: @topic = create(:topic)
     NoMethodError:
       undefined method `cached_slug_changed?' for #<Topic:0x007fb48c41c1a0>
     # ./spec/controllers/topics_controller_spec.rb:43:in `block (3 levels) in <top (required)>'

  25) TopicsController GET show topics should increase view_count
     Failure/Error: @topic = create(:topic)
     NoMethodError:
       undefined method `cached_slug_changed?' for #<Topic:0x007fb48a76f520>
     # ./spec/controllers/topics_controller_spec.rb:43:in `block (3 levels) in <top (required)>'

  26) TopicsController GET show topics should load two topics to read more
     Failure/Error: @topic = create(:topic)
     NoMethodError:
       undefined method `cached_slug_changed?' for #<Topic:0x007fb48a234c68>
     # ./spec/controllers/topics_controller_spec.rb:43:in `block (3 levels) in <top (required)>'

  27) TopicsController New POST create should create a new topic
     Failure/Error: @guide = create(:guide)
     NoMethodError:
       undefined method `cached_slug_changed?' for #<Guide:0x007fb48a20b638>
     # ./spec/controllers/topics_controller_spec.rb:213:in `block (4 levels) in <top (required)>'

  28) TopicsController New POST create should be a leave
     Failure/Error: @guide = create(:guide)
     NoMethodError:
       undefined method `cached_slug_changed?' for #<Guide:0x007fb488fb32b0>
     # ./spec/controllers/topics_controller_spec.rb:213:in `block (4 levels) in <top (required)>'

  29) TopicsController New POST create should have a guide as parent
     Failure/Error: @guide = create(:guide)
     NoMethodError:
       undefined method `cached_slug_changed?' for #<Guide:0x007fb48a098580>
     # ./spec/controllers/topics_controller_spec.rb:213:in `block (4 levels) in <top (required)>'

  30) TopicsController Edit should render edit
     Failure/Error: @topic = create(:topic)
     NoMethodError:
       undefined method `cached_slug_changed?' for #<Topic:0x007fb489182870>
     # ./spec/controllers/topics_controller_spec.rb:249:in `block (3 levels) in <top (required)>'

  31) TopicsController Edit should load all descendants
     Failure/Error: @topic = create(:topic)
     NoMethodError:
       undefined method `cached_slug_changed?' for #<Topic:0x007fb48937e3e0>
     # ./spec/controllers/topics_controller_spec.rb:249:in `block (3 levels) in <top (required)>'

  32) TopicsController Edit POST update should update the topic
     Failure/Error: @topic = create(:topic)
     NoMethodError:
       undefined method `cached_slug_changed?' for #<Topic:0x007fb48c682e08>
     # ./spec/controllers/topics_controller_spec.rb:249:in `block (3 levels) in <top (required)>'

  33) TopicsController POST destroy should delete the topic
     Failure/Error: @topic = create(:topic)
     NoMethodError:
       undefined method `cached_slug_changed?' for #<Topic:0x007fb48c704750>
     # ./spec/controllers/topics_controller_spec.rb:297:in `block (3 levels) in <top (required)>'

  34) TopicsController POST destroy should redirect to home path
     Failure/Error: @topic = create(:topic)
     NoMethodError:
       undefined method `cached_slug_changed?' for #<Topic:0x007fb48c363e70>
     # ./spec/controllers/topics_controller_spec.rb:297:in `block (3 levels) in <top (required)>'

  35) Topic get type is faq
     Failure/Error: faq = create(:faq)
     NoMethodError:
       undefined method `cached_slug_changed?' for #<Faq:0x007fb48a764210>
     # ./spec/models/topic_spec.rb:11:in `block (3 levels) in <top (required)>'

  36) Topic get type is guide
     Failure/Error: guide = create(:guide)
     NoMethodError:
       undefined method `cached_slug_changed?' for #<Guide:0x007fb48a76c690>
     # ./spec/models/topic_spec.rb:17:in `block (3 levels) in <top (required)>'

  37) Topic get type is basic guide
     Failure/Error: basic = create(:basic_guide)
     NoMethodError:
       undefined method `cached_slug_changed?' for #<BasicGuide:0x007fb48a430b48>
     # ./spec/models/topic_spec.rb:23:in `block (3 levels) in <top (required)>'

  38) Topic read more with many leaves should retrieve two next leaves from guide
     Failure/Error: @guide = create(:guide)
     NoMethodError:
       undefined method `cached_slug_changed?' for #<Guide:0x007fb48a431228>
     # ./spec/models/topic_spec.rb:32:in `block (4 levels) in <top (required)>'

  39) Topic read more with many leaves if topic is the last leaf should retrieve the leaves before
     Failure/Error: @guide = create(:guide)
     NoMethodError:
       undefined method `cached_slug_changed?' for #<Guide:0x007fb48928cf68>
     # ./spec/models/topic_spec.rb:32:in `block (4 levels) in <top (required)>'

  40) Topic read more with many leaves if topic is the penultimate leaf should retrieve one leaf before and the last one
     Failure/Error: @guide = create(:guide)
     NoMethodError:
       undefined method `cached_slug_changed?' for #<Guide:0x007fb48c7e4c88>
     # ./spec/models/topic_spec.rb:32:in `block (4 levels) in <top (required)>'

  41) Topic read more with only one more leaf the last one should retrieve the first leaf
     Failure/Error: @guide = create(:guide)
     NoMethodError:
       undefined method `cached_slug_changed?' for #<Guide:0x007fb48c4498a8>
     # ./spec/models/topic_spec.rb:67:in `block (4 levels) in <top (required)>'

  42) Topic read more with only one more leaf the first one should retrieve the last leaf
     Failure/Error: @guide = create(:guide)
     NoMethodError:
       undefined method `cached_slug_changed?' for #<Guide:0x007fb48c4536a0>
     # ./spec/models/topic_spec.rb:67:in `block (4 levels) in <top (required)>'

  43) Topic read more with no more leaf should retrieve any leaf
     Failure/Error: @guide = create(:guide)
     NoMethodError:
       undefined method `cached_slug_changed?' for #<Guide:0x007fb48c45be90>
     # ./spec/models/topic_spec.rb:96:in `block (4 levels) in <top (required)>'

Finished in 0.67021 seconds
49 examples, 43 failures

Failed examples:

rspec ./spec/controllers/basic_guides_controller_spec.rb:26 # BasicGuidesController POST create should create a new basic guide
rspec ./spec/controllers/basic_guides_controller_spec.rb:32 # BasicGuidesController POST create should be a root
rspec ./spec/controllers/basic_guides_controller_spec.rb:45 # BasicGuidesController POST update should update the basic guide
rspec ./spec/controllers/faqs_controller_spec.rb:29 # FaqsController POST create should create a new faq
rspec ./spec/controllers/faqs_controller_spec.rb:35 # FaqsController POST create should be a root
rspec ./spec/controllers/faqs_controller_spec.rb:48 # FaqsController POST update should update the faq
rspec ./spec/controllers/guides_controller_spec.rb:26 # GuidesController POST create should create a new guide
rspec ./spec/controllers/guides_controller_spec.rb:32 # GuidesController POST create should be a root
rspec ./spec/controllers/guides_controller_spec.rb:45 # GuidesController POST update should update the guide
rspec ./spec/controllers/topics_controller_spec.rb:12 # TopicsController GET index should render index
rspec ./spec/controllers/topics_controller_spec.rb:18 # TopicsController GET index should load all roots from Guide
rspec ./spec/controllers/topics_controller_spec.rb:33 # TopicsController GET index frequently questions list should load top questions in Faq
rspec ./spec/controllers/topics_controller_spec.rb:65 # TopicsController GET show faq should render faq
rspec ./spec/controllers/topics_controller_spec.rb:69 # TopicsController GET show faq should load top_questions
rspec ./spec/controllers/topics_controller_spec.rb:73 # TopicsController GET show faq should load all categories
rspec ./spec/controllers/topics_controller_spec.rb:89 # TopicsController GET show faq category should render category show
rspec ./spec/controllers/topics_controller_spec.rb:93 # TopicsController GET show faq category should load all children
rspec ./spec/controllers/topics_controller_spec.rb:97 # TopicsController GET show faq category should load all ancestors
rspec ./spec/controllers/topics_controller_spec.rb:107 # TopicsController GET show basic guide should render basic guide
rspec ./spec/controllers/topics_controller_spec.rb:113 # TopicsController GET show basic guide should load all children
rspec ./spec/controllers/topics_controller_spec.rb:136 # TopicsController GET show guide should render guide
rspec ./spec/controllers/topics_controller_spec.rb:142 # TopicsController GET show guide should load all topics
rspec ./spec/controllers/topics_controller_spec.rb:161 # TopicsController GET show topics should render show
rspec ./spec/controllers/topics_controller_spec.rb:167 # TopicsController GET show topics should load all ancestors
rspec ./spec/controllers/topics_controller_spec.rb:179 # TopicsController GET show topics should increase view_count
rspec ./spec/controllers/topics_controller_spec.rb:186 # TopicsController GET show topics should load two topics to read more
rspec ./spec/controllers/topics_controller_spec.rb:225 # TopicsController New POST create should create a new topic
rspec ./spec/controllers/topics_controller_spec.rb:231 # TopicsController New POST create should be a leave
rspec ./spec/controllers/topics_controller_spec.rb:237 # TopicsController New POST create should have a guide as parent
rspec ./spec/controllers/topics_controller_spec.rb:252 # TopicsController Edit should render edit
rspec ./spec/controllers/topics_controller_spec.rb:258 # TopicsController Edit should load all descendants
rspec ./spec/controllers/topics_controller_spec.rb:274 # TopicsController Edit POST update should update the topic
rspec ./spec/controllers/topics_controller_spec.rb:303 # TopicsController POST destroy should delete the topic
rspec ./spec/controllers/topics_controller_spec.rb:309 # TopicsController POST destroy should redirect to home path
rspec ./spec/models/topic_spec.rb:10 # Topic get type is faq
rspec ./spec/models/topic_spec.rb:16 # Topic get type is guide
rspec ./spec/models/topic_spec.rb:22 # Topic get type is basic guide
rspec ./spec/models/topic_spec.rb:42 # Topic read more with many leaves should retrieve two next leaves from guide
rspec ./spec/models/topic_spec.rb:49 # Topic read more with many leaves if topic is the last leaf should retrieve the leaves before
rspec ./spec/models/topic_spec.rb:57 # Topic read more with many leaves if topic is the penultimate leaf should retrieve one leaf before and the last one
rspec ./spec/models/topic_spec.rb:78 # Topic read more with only one more leaf the last one should retrieve the first leaf
rspec ./spec/models/topic_spec.rb:86 # Topic read more with only one more leaf the first one should retrieve the last leaf
rspec ./spec/models/topic_spec.rb:104 # Topic read more with no more leaf should retrieve any leaf
```

**Comment by guiocavalcanti** [comment]
Don't bother, it was a database issue. :+1:
